### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by nhuhoa** [XuegongLab/HGC#2]
Dear authors, 

Your package looks quite promising and I try to apply it to my work, however, I met some issues while installing this package. I just want to inform you here. 

# Issue 1: installation error vignette, I install your program using R in MacOs, linux
E> * checking vignette meta-information ... ERROR
E> Output(s) listed in ‘build/vignette.rds’ but not in package:
E>   ‘inst/doc/HGC.html’
E> Run R CMD build without --no-build-vignettes to re-create

So, in order to run program (Just ignore vignettes, I try to generate a tar.gz file first): 
go to git folder and run commands:
R CMD build . --no-build-vignettes
R CMD install .

# Issue 2: error with testing script
Pollen.PCs <- Pollen[["PCs"]]
Pollen.Label.Tissue <- Pollen[["Tissue"]]
Pollen.Label.CellLine <- Pollen[["CellLine"]]
Pollen.SNN <- SNN.Construction(mat = Pollen.PCs, k = 25, threshold = 0.15)
Pollen.ClusteringTree <- HGC.dendrogram(G = Pollen.SNN)

Pollen.ClusteringTree
plot(Pollen.ClusteringTree)  ### Error here, Error in graphics:::plotHclust(n1, merge, height, order(x$order), hang,  : invalid dendrogram input

Pollen.ClusteringTree$merge[1:3,1:3]  # debug, issue here
##Error in Pollen.ClusteringTree$merge[1:3, 1:3] : subscript out of bounds

Thanks, 
Best, 
Hoa

**Comment by zouzh14** [comment]
Dear Hao,

Thanks for your support of our package and the report.

For issue 1, it came from the lack of HGC.html file and we added it in the new version. We believe now it is okay to install with the R command:
`devtools::install_github("XuegongLab/HGC", ref = "HGC4oldRVersion")
`

For issue 2, we are checking the message from graphics:::plotHclust. Meanwhile, you could use plot function for the dendrogram object:
`Pollen.Dendrogram <- as.dendrogram(Pollen.ClusteringTree)
plot(Pollen.Dendrogram)
`
And we strongly recommend to try the visualization functions in HGC to plot the tree.

And the "subscript out of bounds" for the merging matrix is not an error, because in design the matrix has 2 columns.

Best,
Zou Ziheng

**Comment by zouzh14** [comment]
Dear Hao,

Thanks for your support of our package and the report.

For issue 1, it came from the lack of HGC.html file and we added it in the new version. We believe now it is okay to install with the R command:
devtools::install_github("XuegongLab/HGC", ref = "HGC4oldRVersion")

For issue 2, we are checking the message from graphics:::plotHclust. Meanwhile, you could use plot function for the dendrogram object:
Pollen.Dendrogram <- as.dendrogram(Pollen.ClusteringTree) plot(Pollen.Dendrogram)
And we strongly recommend to try the visualization functions in HGC to plot the tree.

And the "subscript out of bounds" for the merging matrix is not an error, because in design the matrix has 2 columns.

Best,
Zou Ziheng

**Comment by nhuhoa** [comment]
Dear Zouzh, 

Thanks a lot for your support. Yes, the installation works well right now with your change. The visualization plot works too.  Last time I tested there is no tree dendrogram plot that's why I tried to use another plotting function to test. It looks perfect with your viz functions. 

Thanks, 
Best, 
Hoa Tran
